### ISSUE TITLE
The parser doesn't parse fragments

### ISSUE THREAD

**Issue by intagaming** [ota-meshi/astro-eslint-parser#77] opened 2022-08-08 14:32 UTC
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I'm using [eslint-plugin-astro](https://github.com/ota-meshi/eslint-plugin-astro).  (`*.astro` file linting does not work with the parser alone. You should also use eslint-plugin-astro with it.)
- [X] I'm sure the problem is a parser problem. (If you are not sure, search for the issue in [eslint-plugin-astro](https://github.com/ota-meshi/eslint-plugin-astro) repo and open the issue in [eslint-plugin-astro](https://github.com/ota-meshi/eslint-plugin-astro) repo if there is no solution.
- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.

### What version of ESLint are you using?

8.21.0

### What version of `eslint-plugin-astro` and ` astro-eslint-parser` are you using?

- astro-eslint-parser@0.4.5, judged by the package-lock.json
- eslint-plugin-astro@0.16.0

### What did you do?

<details>
<summary>Configuration</summary>

.eslintrc.js:

```
module.exports = {
  env: {
    node: true,
  },
  settings: {
    react: {
      version: "detect",
    },
  },
  extends: ["plugin:astro/recommended"],
  overrides: [
    {
      // Define the configuration for `.astro` file.
      files: ["*.astro"],
      // Allows Astro components to be parsed.
      parser: "astro-eslint-parser",
      // Parse the script in `.astro` as TypeScript by adding the following configuration.
      // It's the setting you need when using TypeScript.
      parserOptions: {
        parser: "@typescript-eslint/parser",
        extraFileExtensions: [".astro"],
      },
      rules: {
        // override/add rules settings here, such as:
        // "astro/no-set-html-directive": "error"
      },
    },
    {
      files: ["*.ts", "*.tsx"],
      parser: "@typescript-eslint/parser",
      extends: [
        "eslint:recommended",
        "plugin:react/recommended",
        "plugin:react/jsx-runtime",
        "plugin:@typescript-eslint/recommended",
        "plugin:@typescript-eslint/recommended-requiring-type-checking",
      ],
      parserOptions: {
        project: ["./tsconfig.json"],
      },
    },
  ],
};

```
</details>

```astro
{seo.openGraph.article && (<>
    <meta property="article:published_time" content={seo.openGraph.article.publishedTime} />
    <meta property="article:modified_time" content={seo.openGraph.article.modifiedTime} />
    {seo.openGraph.article.authors.map(author => (
    <meta property="article:author" content={author} />
    ))}
  </>)}
```

It's an expression inside a fragment. Sorry for the un-generic example, but I have the entire code [here](https://github.com/intagaming/hxann.com/blob/main/src/layouts/BaseLayout.astro).

### What did you expect to happen?

The ESLint passes without error.

### What actually happened?

```
❯ npm run lint

> @example/basics@0.0.1 lint
> eslint . --ext .js,.jsx,.ts,.tsx,.astro


/Users/an7/files/dev/hxann.com/src/layouts/BaseLayout.astro
  77:4  error  Parsing error: Unknown token at 2281, expected: "class", actual: "ad>\n\n<body"

✖ 1 problem (1 error, 0 warnings)

```

### Link to Minimal Reproducible Example

https://github.com/intagaming/hxann.com

**Comment by ota-meshi** [comment] 2022-08-08 15:21
Thank you for posting issue.

The problem seems to be that `@astro/compiler` is not returning the correct AST.
Try with prettier-plugin-astro, which uses the same package, and your template will look like this:

```astro
---
// ... 
---

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <!-- ... -->
    <meta property="og:image" content={seo.openGraph.image} />
  </head>{seo.openGraph.article && (
    <>
      <meta
        property="article:published_time"
        content={seo.openGraph.article.publishedTime}
      />
      <meta
        property="article:modified_time"
        content={seo.openGraph.article.modifiedTime}
      />
      {seo.openGraph.article.authors.map((author) => (
        <meta property="article:author" content={author} />
      ))}
    </>
  )}

  <script is:inline>
    // ...
  </script>

  <!-- ... -->

  <link
    href="https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700&family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,300;1,400;1,500;1,600;1,700;1,800&display=swap"
    rel="stylesheet"
  />

  <div class="flex flex-col min-h-screen">
    <NavBar client:load entries={navBarEntries} currentPath={path} />
    <div class="flex-1 dark:bg-neutral-900">
      <slot />
    </div>
    <Footer />
  </div>
</html>
```

Looking at the results, the `</head>` is misplaced and the `<body>` is missing.

DEMO: https://stackblitz.com/edit/github-prettier-plugin-astro-demo-c7r92s?file=src%2Fpages%2Findex.astro

**Comment by ota-meshi** [comment] 2022-08-08 15:26
I think we should open an issue on the [@astrojs/compiler] repository and provide a minimal reproducible repository.

[@astrojs/compiler]: https://github.com/withastro/compiler

**Comment by intagaming** [comment] 2022-08-08 16:43
> I think we should open an issue on the [@astrojs/compiler](https://github.com/withastro/compiler) repository and provide a minimal reproducible repository.

I'm not sure what's the best way to provide a minimal reproducible project of this issue. The `prettier.format` part, I kinda understand roughly that it formats the Astro code, but nothing more. If you or anyone can make one and open an issue that would be much appreciated. I think best I can do is making one from the Astro's Getting Started, which sounds mediocre and might not be too minimal...

**Comment by ota-meshi** [comment] 2022-08-08 16:54
I don't have time to sort out the information to open an issue for the time being.
If you can't do that, it probably won't fix it.

**Comment by ota-meshi** [comment] 2022-11-27 08:11
Using it with the latest @astro/compiler seems to solve the problem. So I will close this issue.

**Closed by ota-meshi** 2022-11-27 08:11 UTC
Labels: upstream issue
